### ISSUE TITLE
tickCountIndex function issue

### ISSUE THREAD

**Issue by Geervesh** [Redsift/d3-rs-bars#6]
To customise the number of ticks for Value using tickCountValue function works perfectly but using tickCountIndex function for Index it seems to be doing any thing. 

Examples to showcase the issue: 
[Brick Example](https://bricks.redsift.cloud/reusable/d3-rs-bars.svg?_datum=%5B1,2,3,10,20%5D&tickCountIndex=1&tickCountValue=2)
[CodePen Example](http://codepen.io/geervesh/pen/dpqzVm)

**Comment by rahulpowar** [comment]
Provide detail
